FROM oven/bun:latest AS build

WORKDIR /app

COPY package.json ./
COPY bun.lock ./
RUN bun install

COPY . .

ARG VITE_API_URL=http://localhost:3000
ENV VITE_API_URL=$VITE_API_URL

RUN bun run build

FROM oven/bun:latest

WORKDIR /app

COPY package.json ./
COPY bun.lock ./
RUN bun install

COPY --from=build /app/dist ./dist

EXPOSE 4173

CMD ["bun", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]