services:
  db:
    image: postgres:15-alpine
    container_name: m5_postgres
    environment:
      POSTGRES_USER: m5user
      POSTGRES_PASSWORD: m5password
      POSTGRES_DB: m5pager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: m5_backend
    command: sh -c "bunx prisma migrate deploy && bun run dev"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://m5user:m5password@db:5432/m5pager?schema=public
      - MQTT_BROKER=bda50acbea674d6ab52f378c2e72b560.s1.eu.hivemq.cloud
      - MQTT_TRANSPORT=mqtts
      - MQTT_PORT=8883
      - MQTT_WEBSOCKET_PORT=8884
      - MQTT_USER=hivemq.webclient.1774882342885
      - "MQTT_PASS=5AsV$$*UDt!271wnKaZ:i"
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - audio_files:/audio:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: m5_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - dev
    restart: unless-stopped

  cloud_worker:
    build:
      context: ./cloud_worker
    container_name: m5_cloud_worker
    environment:
      - DATABASE_URL=postgresql://m5user:m5password@db:5432/m5pager
      - MQTT_BROKER=bda50acbea674d6ab52f378c2e72b560.s1.eu.hivemq.cloud
      - MQTT_PORT=8883
      - MQTT_USER=hivemq.webclient.1774882342885
      - "MQTT_PASS=5AsV$$*UDt!271wnKaZ:i"
      - AUDIO_DIR=/audio
      - PCM_SAMPLE_RATE=16000
      - WAV_RATE_FACTOR=1.0
      - PCM_CHANNELS=1
      - PCM_SAMPLE_WIDTH=2
      - PAD_TO_EXPECTED_BYTES=true
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./cloud_worker:/app
      - audio_files:/audio
    restart: unless-stopped

volumes:
  postgres_data:
  audio_files: