// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Build-time fallback prevents Docker image builds from failing when
// DATABASE_URL is only provided at container runtime by Docker Compose.
const databaseUrl =
  process.env.DATABASE_URL ||
  "postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
